### ISSUE TITLE
Segmentation fault when processing a set Alarm

### ISSUE THREAD

**Issue by peter-mount** [peter-mount/nre-feeds#7]
An inbound message that sets an alarm causes a segmentation fault & the d3 service dies.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7ee20d]

goroutine 11 [running]:
github.com/etcd-io/bbolt.(*Tx).Bucket(...)
	/go/pkg/mod/github.com/etcd-io/bbolt@v1.3.1-etcd.8.0.20181208010242-22d122a8b910/tx.go:101
github.com/peter-mount/nre-feeds/darwind3.(*DarwinD3).setAlarm(0xc0001ba000, 0x0, 0xc00059ec60, 0x0, 0xc0005d7788)
	/work/darwind3/alarms.go:53 +0x9d
github.com/peter-mount/nre-feeds/darwind3.(*DarwinD3).SetAlarm.func1(0xc0005a55e0, 0x90e5c8, 0xc0005a55e0)
	/work/darwind3/alarms.go:44 +0x3c
github.com/etcd-io/bbolt.(*DB).Update(0xc0001b61e0, 0xc0003fa8a0, 0x0, 0x0)
	/go/pkg/mod/github.com/etcd-io/bbolt@v1.3.1-etcd.8.0.20181208010242-22d122a8b910/db.go:670 +0x90
github.com/peter-mount/nre-feeds/darwind3.(*DarwinD3).Update(...)
	/work/darwind3/cache.go:117
github.com/peter-mount/nre-feeds/darwind3.(*DarwinD3).SetAlarm(0xc0001ba000, 0xc00059ec60, 0xc0005d78b8, 0x40b509)
	/work/darwind3/alarms.go:43 +0x80
github.com/peter-mount/nre-feeds/darwind3.(*RttiAlarm).Process(0xc00059ec60, 0xc0001a50a0, 0x0, 0xc0005d78c0)
	/work/darwind3/alarms.go:116 +0x84
github.com/peter-mount/nre-feeds/darwind3.(*UR).Process(0xc0001af420, 0xc0001a50a0, 0x1, 0xc0001a50a0)
	/work/darwind3/updateResponse.go:95 +0x70
github.com/peter-mount/nre-feeds/darwind3.(*Pport).Process.func1(0xc0001a50a0, 0xc0001a50a0, 0x0)
	/work/darwind3/pport.go:92 +0x3c
github.com/peter-mount/nre-feeds/darwind3.(*DarwinD3).ProcessUpdate(...)
	/work/darwind3/processPport.go:25
github.com/peter-mount/nre-feeds/darwind3.(*Pport).Process(0xc0001ccd80, 0xc0001ba000, 0xc0001ccd80, 0x0)
	/work/darwind3/pport.go:91 +0x29b
github.com/peter-mount/nre-feeds/darwind3.(*DarwinD3).consume(0xc0001ba000, 0xa000e0, 0xc0000970e0, 0xc0005c1290, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/work/darwind3/consumer.go:45 +0x343
github.com/peter-mount/nre-feeds/darwind3.(*DarwinD3).BindConsumer.func1(0xc000066960, 0xc0001ba000)
	/work/darwind3/consumer.go:28 +0xef
created by github.com/peter-mount/nre-feeds/darwind3.(*DarwinD3).BindConsumer
	/work/darwind3/consumer.go:25 +0x222
```
the culprit seems to be:
```go
return tx.Bucket([]byte(alarmBucket)).Put([]byte(a.ID), b)
```
which calls tx.Bucket & this is line tx.go:101
```go
return tx.root.Bucket(name)
```

**Comment by peter-mount** [comment]
Found that both the SetAlarm & DeleteAlarm functions were using a nil bbolt.Tx instance & not the one provided, a simple typo
